version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    restart: always